#!/usr/bin/env node
// @ts-nocheck
/**
 * Pack example apps and bundle the W2 browser examples spike for Playwright.
 */

import { cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { buildSync } from "esbuild";
import { verifyPackage } from "../../packages/app-registry/dist/index.js";
import { NodeCryptoProvider } from "../../packages/reticulum-ts/dist/index.js";
import { runInit, runPack } from "../../packages/cli/dist/commands/index.js";

const examplesRoot = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(examplesRoot, "../..");
const harnessRoot = join(repoRoot, "apps/harness-mobile");
const appsExamplesDir = resolve(examplesRoot, "../../apps/examples");
const EXAMPLE_NAMES = ["chat", "file-drop", "board"];

function bytesToHex(bytes) {
  return Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("");
}

async function packExample(name) {
  const cwd = mkdtempSync(join(tmpdir(), `tp-web-example-${name}-`));
  const appDir = join(cwd, name);
  cpSync(join(appsExamplesDir, name), appDir, { recursive: true });

  try {
    const initCode = await runInit({ cwd, identityPassphrase: "conformance identity passphrase", args: [] });
    if (initCode !== 0) {
      throw new Error(`tp init failed for ${name}`);
    }

    const packCode = await runPack({ cwd, args: [name, "--out", `${name}.tpkg`] });
    if (packCode !== 0) {
      throw new Error(`tp pack failed for ${name}`);
    }

    const provider = new NodeCryptoProvider();
    const archive = new Uint8Array(readFileSync(join(cwd, `${name}.tpkg`)));
    const verified = verifyPackage(provider, archive, { hostApiVersion: "0.1.0" });

    return {
      name: verified.manifest.name,
      version: verified.manifest.version,
      capabilities: verified.manifest.capabilities ?? [],
      publisherPublicKey: verified.manifest.publisherPublicKey,
      archiveHex: bytesToHex(archive),
      archiveBytes: archive.length
    };
  } finally {
    rmSync(cwd, { recursive: true, force: true });
  }
}

const build = spawnSync(
  "npm",
  [
    "run",
    "build",
    "--workspace=@twistedpear/miniapp-runtime",
    "--workspace=@twistedpear/host-core",
    "--workspace=@twistedpear/reticulum-ts",
    "--workspace=@twistedpear/app-registry",
    "--workspace=@twistedpear/cas-256t"
  ],
  { cwd: repoRoot, stdio: "inherit" }
);
if (build.status !== 0) {
  process.exit(build.status ?? 1);
}

const workerBuild = spawnSync("node", ["scripts/build-web-worker.mjs"], {
  cwd: harnessRoot,
  stdio: "inherit"
});
if (workerBuild.status !== 0) {
  process.exit(workerBuild.status ?? 1);
}

const packed = {};
for (const name of EXAMPLE_NAMES) {
  packed[name] = await packExample(name);
  console.log(`web-examples: packed ${name} (${packed[name].archiveBytes} bytes)`);
}

writeFileSync(
  join(examplesRoot, "fixtures.mjs"),
  `/** Generated by conformance/web-examples/build.mjs — do not edit. */\nexport const EXAMPLE_FIXTURES = ${JSON.stringify(packed, null, 2)};\n`
);

buildSync({
  entryPoints: [join(examplesRoot, "entry.mjs")],
  bundle: true,
  platform: "browser",
  format: "iife",
  globalName: "TwistedPearWebExamples",
  outfile: join(examplesRoot, "examples.bundle.js"),
  logLevel: "warning"
});

writeFileSync(
  join(examplesRoot, "web-core.worker.js"),
  readFileSync(join(harnessRoot, "public/web-core.worker.js"), "utf8")
);

console.log("web-examples bundle written");
