import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/node_modules/**",
      "site/**",
      "archive/**",
      "**/*.gen.ts",
      "**/*.generated.js",
      "**/*.generated.mjs",
      "packages/guida-twistedpear/seed/**",
      // Built web worker bundle, gitignored and regenerated by build:web-worker.
      // Its vendored eslint-disable comments name rules this config never
      // registers for .js, so linting it reports only "rule not found" noise.
      "apps/harness-mobile/public/web-core.worker.js",
    ],
  },
  {
    files: ["packages/**/*.{ts,tsx}", "apps/**/*.{ts,tsx}"],
    plugins: { "@typescript-eslint": tseslint.plugin },
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-floating-promises": "warn",
      "@typescript-eslint/no-misused-promises": "warn",
      "@typescript-eslint/await-thenable": "warn",
      "@typescript-eslint/require-await": "warn",
      "@typescript-eslint/no-unnecessary-condition": "warn",
    },
  },
);
