import tsParser from "@typescript-eslint/parser";
import sonarjs from "eslint-plugin-sonarjs";

/**
 * Cognitive complexity, measured rather than enforced.
 *
 * This is deliberately a separate config rather than an addition to
 * `eslint.complexity.config.js`. That file feeds `complexity-ratchet.json`,
 * where every finding is a pinned debt entry; adding a rule that reports once
 * per function would add several thousand entries to a baseline whose whole
 * purpose is to shrink. It also measures something different: ESLint's
 * `complexity` rule is cyclomatic — one point per branch — while cognitive
 * complexity charges nesting progressively and forgives shorthand that reads
 * linearly. A function can be cyclomatically simple and cognitively awful.
 *
 * The threshold is 0 so that every function reports its score. The survey never
 * fails, so a "violation" here is a measurement, not a defect.
 */
const ignores = [
  "**/node_modules/**",
  "**/dist/**",
  "site/**",
  "archive/**",
  "**/*.gen.ts",
  "**/*.generated.mjs",
  "**/*.generated.js",
  "packages/guida-twistedpear/seed/**",
  "conformance/guida-compiler/**",
  "**/bundle.js",
  "**/*.bundle.js",
  "**/*.bundle.mjs",
  "**/*.bundle",
  "apps/harness-mobile/android/**",
  "apps/harness-mobile/ios/**",
  "apps/harness-mobile/public/**",
  "apps/handbook/generated/**",
  "apps/handbook/seeds/**",
  "apps/host-desktop/src/renderer/vendor/**",
  "packages/reticulum-ts/docs/api/**",
  "conformance/docs/.tmp-handbook-capture/**",
  // Generated by the web conformance builders, and gitignored. These are
  // bundles tens of thousands of lines long; measuring them would report the
  // complexity of everything they inline, several times over.
  "conformance/**/web-core.worker.js",
  "conformance/**/web-hyper-fetch.js",
  "conformance/**/fixtures.mjs",
  "conformance/**/publisher-data.mjs",
  "conformance/web-storage/fixture.mjs",
  // Concat inputs for the worklet entries. Two of them split mid-object-literal
  // and do not parse alone; the assembled files are committed and measured.
  "apps/harness-mobile/worklet/entry-part-*.mjs",
  "apps/harness-mobile/worklet/web-entry-part-*.mjs",
];

export default [
  { ignores },
  {
    files: ["**/*.{js,mjs,cjs}"],
    plugins: { sonarjs },
    rules: { "sonarjs/cognitive-complexity": ["warn", 0] },
  },
  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parser: tsParser,
      parserOptions: { ecmaVersion: 2022, sourceType: "module" },
    },
    plugins: { sonarjs },
    rules: { "sonarjs/cognitive-complexity": ["warn", 0] },
  },
];
