apply plugin: 'com.android.library'
apply from: new File(rootProject.rootDir, '../../../conformance/android-native/jacoco-module.gradle')

group = 'network.twistedpear.harness'
version = '0.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()
useExpoPublishing()

android {
  namespace "expo.modules.twistedpear.blebridge"
  defaultConfig {
    versionCode 1
    versionName "0.0.0"
  }
}

dependencies {
  testImplementation "junit:junit:4.13.2"
  testImplementation "org.mockito:mockito-core:5.14.2"
}
