#!/usr/bin/env node
/**
 * Pack signed Handbook and bundle the Playwright browser Handbook spike.
 */

import { readFileSync, writeFileSync, cpSync, mkdirSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { buildSync } from "esbuild";
import { verifyPackage } from "../../packages/app-registry/dist/index.js";
import { NodeCryptoProvider } from "../../packages/reticulum-ts/dist/index.js";
import { HOST_API_VERSION } from "../../packages/miniapp-runtime/dist/host-api.js";
import { runInit, runPack } from "../../packages/cli/dist/commands/index.js";

const handbookRoot = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(handbookRoot, "../..");
const harnessRoot = join(repoRoot, "apps/harness-mobile");
const handbookDir = join(repoRoot, "apps/handbook");

function bytesToHex(bytes) {
  return Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("");
}

function buildHandbookContent() {
  const result = spawnSync(process.execPath, [join(handbookDir, "build.mjs")], {
    cwd: handbookDir,
    encoding: "utf8"
  });
  if (result.status !== 0) {
    throw new Error(`handbook content build failed:\n${result.stdout}\n${result.stderr}`);
  }
  console.log(result.stdout.trim());
}

async function packHandbookFixture() {
  const cwd = mkdtempSync(join(tmpdir(), "tp-web-handbook-"));
  const appDir = join(cwd, "handbook");
  mkdirSync(appDir, { recursive: true });
  cpSync(join(handbookDir, "app.manifest.json"), join(appDir, "app.manifest.json"));
  cpSync(join(handbookDir, "bundle.js"), join(appDir, "bundle.js"));

  try {
    const initCode = await runInit({ cwd, identityPassphrase: "conformance identity passphrase", args: [] });
    if (initCode !== 0) {
      throw new Error("tp init failed for handbook");
    }

    const packCode = await runPack({ cwd, args: ["handbook", "--out", "handbook.tpkg"] });
    if (packCode !== 0) {
      throw new Error("tp pack failed for handbook");
    }

    const provider = new NodeCryptoProvider();
    const archive = new Uint8Array(readFileSync(join(cwd, "handbook.tpkg")));
    const verified = verifyPackage(provider, archive, { hostApiVersion: HOST_API_VERSION });
    const catalog = JSON.parse(readFileSync(join(handbookDir, "generated/catalog.json"), "utf8"));

    return {
      appId: verified.manifest.name,
      version: verified.manifest.version,
      capabilities: verified.manifest.capabilities ?? [],
      publisherPublicKey: verified.manifest.publisherPublicKey,
      archiveHex: bytesToHex(archive),
      archiveBytes: archive.length,
      chapterIds: catalog.chapters.map((chapter) => chapter.id),
      chapterTitles: Object.fromEntries(catalog.chapters.map((chapter) => [chapter.id, chapter.title])),
      appletIds: catalog.applets.map((applet) => applet.id),
      appletTitles: Object.fromEntries(catalog.applets.map((applet) => [applet.id, applet.title])),
      applets: catalog.applets.map((applet) => ({
        id: applet.id,
        expectations: applet.expectations
      }))
    };
  } finally {
    rmSync(cwd, { recursive: true, force: true });
  }
}

const build = spawnSync(
  "npm",
  [
    "run",
    "build",
    "--workspace=@twistedpear/miniapp-runtime",
    "--workspace=@twistedpear/host-core",
    "--workspace=@twistedpear/reticulum-ts",
    "--workspace=@twistedpear/app-registry",
    "--workspace=@twistedpear/cas-256t",
    "--workspace=@twistedpear/cli"
  ],
  { cwd: repoRoot, stdio: "inherit" }
);
if (build.status !== 0) {
  process.exit(build.status ?? 1);
}

const workerBuild = spawnSync("node", ["scripts/build-web-worker.mjs"], {
  cwd: harnessRoot,
  stdio: "inherit"
});
if (workerBuild.status !== 0) {
  process.exit(workerBuild.status ?? 1);
}

buildHandbookContent();
const fixture = await packHandbookFixture();
console.log(`web-handbook: packed handbook (${fixture.archiveBytes} bytes)`);

writeFileSync(
  join(handbookRoot, "fixtures.mjs"),
  `/** Generated by conformance/web-handbook/build.mjs — do not edit. */\nexport const HANDBOOK_FIXTURE = ${JSON.stringify(fixture, null, 2)};\n`
);

buildSync({
  entryPoints: [join(handbookRoot, "entry.mjs")],
  bundle: true,
  platform: "browser",
  format: "esm",
  outfile: join(handbookRoot, "handbook.bundle.js"),
  logLevel: "warning"
});

writeFileSync(
  join(handbookRoot, "web-core.worker.js"),
  readFileSync(join(harnessRoot, "public/web-core.worker.js"), "utf8")
);

console.log("web-handbook bundle written");
