/**
 * Hostile-author P0 catalog. Expected verdicts are the plan's; measured
 * verdicts are what baseline.mjs confirmed against the tree.
 *
 * UNMEASURED means INFORMED cannot be decided without a ConsentRecord (P1)
 * or the render oracle (P2). It is not a pass. The plan's tables list 27
 * scenario ids (HA-01..05, 10..15, 20..24, 30..36, 40..43).
 */
export const SCENARIOS = [
  {
    id: "HA-01",
    expected: "INFORMED",
    measured: "UNCONTROLLED",
    marker: "pinnedKeys",
    absent: "confusable",
    file: "packages/app-registry/src/catalog.ts",
    note: "Catalog appId is publisherKeyHash:name; two keys both appear. Homoglyphs are folded into confusableWith.",
  },
  {
    id: "HA-02",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "pinnedKey !== summary.publisherKeyHash",
    file: "packages/app-registry/src/catalog.ts",
    note: "canAcceptIngest refuses a pinned publisher-key mismatch for the same catalog id.",
  },
  {
    id: "HA-03",
    expected: "INFORMED",
    measured: "UNMEASURED",
    marker: '"trust-import"',
    file: "packages/miniapp-runtime/src/confirm.ts",
    note: "trust-import confirmation kind exists; wording is not transcript-checked.",
  },
  {
    id: "HA-04",
    expected: "INFORMED",
    measured: "UNMEASURED",
    marker: '"install"',
    file: "packages/miniapp-runtime/src/confirm.ts",
    note: "install confirmation exists; post-fetch review is not transcript-checked.",
  },
  {
    id: "HA-05",
    expected: "INFORMED",
    measured: "UNMEASURED",
    marker: "apps:install",
    file: "packages/miniapp-runtime/src/capabilities.ts",
    note: "apps:install is confirmation-gated; the second review is not a separate transcript.",
  },
  {
    id: "HA-10",
    expected: "INFORMED",
    measured: "UNMEASURED",
    marker: "lxmf:send",
    file: "packages/miniapp-runtime/src/capabilities.ts",
    note: "Canonical grant text exists; destination-picked-by-app is not transcript-checked.",
  },
  {
    id: "HA-11",
    expected: "BLOCKED then INFORMED",
    measured: "UNCONTROLLED",
    absent: "isNewSinceLastApproval",
    file: "packages/miniapp-runtime/src/confirm.ts",
    note: "No capability-delta review on update. APPR-UPDATE-DELTA is still open.",
  },
  {
    id: "HA-12",
    expected: "BLOCKED",
    measured: "UNCONTROLLED",
    marker: "Readonly<Record<string, string>>",
    file: "packages/miniapp-runtime/src/confirm.ts",
    note: "Summary values are sanitized of newlines and bidi overrides before chrome sees them.",
  },
  {
    id: "HA-13",
    expected: "BLOCKED",
    measured: "UNCONTROLLED",
    marker: "DEFAULT_CONFIRMATION_TIMEOUT_MS",
    absent: "rateLimit",
    file: "packages/miniapp-runtime/src/confirm.ts",
    note: "ConfirmationRateLimiter refuses a fourth confirmation in the same window.",
  },
  {
    id: "HA-14",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "rejects preview grants that escalate",
    file: "packages/miniapp-runtime/test/apps.test.ts",
    note: "AppsService.preview rejects grants outside the declared manifest.",
  },
  {
    id: "HA-15",
    expected: "INFORMED",
    measured: "UNMEASURED",
    absent: "ConsentRecord",
    file: "packages/miniapp-runtime/src/confirm.ts",
    note: "No consent transcript to mark unused authorities.",
  },
  {
    id: "HA-20",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "CHROME-R8",
    file: "packages/miniapp-runtime/src/ui/chrome-lexicon.ts",
    note: "Grant-screen Approve/Deny pair is CHROME-R8 layout imitation.",
  },
  {
    id: "HA-21",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "CHROME-R9",
    file: "packages/miniapp-runtime/src/ui/chrome-lexicon.ts",
    note: "Recovery-phrase solicitation is CHROME-R9.",
  },
  {
    id: "HA-22",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "this app needs",
    file: "packages/miniapp-runtime/src/ui/chrome-lexicon.ts",
    note: "Softened permissions pre-prompt is CHROME-R8 reserved lexicon.",
  },
  {
    id: "HA-23",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "host update required",
    file: "packages/miniapp-runtime/src/ui/chrome-lexicon.ts",
    note: "Fake host-update banner is CHROME-R8 reserved lexicon.",
  },
  {
    id: "HA-24",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "TwistedPear has verified",
    file: "packages/miniapp-runtime/src/ui/chrome-lexicon.ts",
    note: "TwistedPear authority claim is CHROME-R8 reserved lexicon.",
  },
  {
    id: "HA-30",
    expected: "BLOCKED",
    measured: "UNCONTROLLED",
    absent: "EgressOffer",
    file: "packages/miniapp-runtime/src/capabilities.ts",
    note: "Granted lxmf:send names no destination. Security-review F4. CAP-EGRESS-OFFER is open.",
  },
  {
    id: "HA-31",
    expected: "INFORMED + CONTAINED",
    measured: "CONTAINED",
    marker: "sanitize",
    file: "packages/miniapp-runtime/src/services/ai.ts",
    note: "Host-fixed endpoint and budgets exist; grant wording is not transcript-checked.",
  },
  {
    id: "HA-32",
    expected: "CONTAINED",
    measured: "CONTAINED",
    marker: "ANNOUNCE_CROSS_APP_SCOPE",
    file: "conformance/hostile-apps/capability-probes.mjs",
    note: "Own-namespace plus announce appData ceiling. Not destination-scoped.",
  },
  {
    id: "HA-33",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "cross-app announce subscribe",
    file: "conformance/hostile-apps/capability-probes.mjs",
    note: "announce:subscribe into another app's namespace is ANNOUNCE_CROSS_APP_SCOPE.",
  },
  {
    id: "HA-34",
    expected: "CONTAINED",
    measured: "CONTAINED",
    marker: "resourceId",
    file: "packages/miniapp-runtime/src/services/resource.ts",
    note: "Fetch names a host resource id, not an app URL. Destination is host-fixed.",
  },
  {
    id: "HA-35",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "stale launch-time grant",
    file: "conformance/hostile-apps/capability-probes.mjs",
    note: "GrantStore.delete denies the next dispatch. In-flight streams are not asserted here.",
  },
  {
    id: "HA-36",
    expected: "CONTAINED",
    measured: "UNCONTROLLED",
    absent: "EgressOffer",
    file: "packages/miniapp-runtime/src/capabilities.ts",
    note: "Benign-until-flag requires destination scoping. CAP-EGRESS-OFFER is open.",
  },
  {
    id: "HA-40",
    expected: "CONTAINED",
    measured: "UNMEASURED",
    marker: "apps:install",
    file: "packages/miniapp-runtime/src/capabilities.ts",
    note: "Invite provenance is not a broker-observable in this baseline.",
  },
  {
    id: "HA-41",
    expected: "BLOCKED",
    measured: "BLOCKED",
    marker: "blockedApps",
    file: "packages/protocol/src/lxmf-moderation.ts",
    note: "blockedApps blocks one app id without blocking another on the same source hash.",
  },
  {
    id: "HA-42",
    expected: "CONTAINED",
    measured: "CONTAINED",
    marker: "DEFAULT_ANNOUNCE_RATE_TARGET",
    file: "packages/protocol/src/announce-rate.ts",
    note: "Transport announce ingress is rate-limited. App-level publish still uses broker quotas.",
  },
  {
    id: "HA-43",
    expected: "INFORMED",
    measured: "UNMEASURED",
    marker: '"install"',
    file: "packages/miniapp-runtime/src/confirm.ts",
    note: "Same install confirmation as HA-04; lure-from-contact is not separately checked.",
  },
];
