import { LINK_ENABLED_MODES,LINK_ESTABLISHMENT_TIMEOUT_PER_HOP,LINK_INITIATOR_ENTROPY_SIZE,LINK_KEEPALIVE,LINK_KEEPALIVE_MAX_RTT,LINK_KEEPALIVE_MIN,LINK_KEEPALIVE_TIMEOUT_FACTOR,LINK_MODE_BYTEMASK,LINK_MODE_DEFAULT,LINK_MTU_BYTEMASK,LINK_PROOF_BODY_SIZE,LINK_PROOF_MTU_SIZE,LINK_PROOF_SIGNATURE_SIZE,LINK_REQUEST_ECPUB_SIZE,LINK_RESPONSE_MAX_GRACE_TIME,LINK_RESPONDER_ENTROPY_SIZE,LINK_STALE_FACTOR,LINK_STALE_GRACE,LINK_TRAFFIC_TIMEOUT_FACTOR,LINK_WATCHDOG_MAX_SLEEP_MS,LINK_X25519_KEY_SIZE,LinkMode,LinkResourceStrategy,LinkStatus,LinkTeardownReason,shouldAcceptLinkIdentifyNow,initialAcceptLinkIdentifyState,stepAcceptLinkIdentifyWithActions,shouldAcceptLinkOwnerPublicKeyNow,initialAcceptLinkOwnerPublicKeyState,stepAcceptLinkOwnerPublicKeyWithActions,shouldAcceptLinkRttNow,initialAcceptLinkRttState,stepAcceptLinkRttWithActions,shouldAllowIdentifyOnLink,initialIdentifyOnLinkAllowState,stepIdentifyOnLinkAllowWithActions,shouldAllowLinkRequest,initialLinkRequestAllowState,stepLinkRequestAllowWithActions,shouldAllowLinkSend,initialLinkSendAllowState,stepLinkSendAllowWithActions,shouldAllowPerformLinkHandshake,initialPerformLinkHandshakeAllowState,stepPerformLinkHandshakeAllowWithActions,shouldAllowProveLink,initialProveLinkAllowState,stepProveLinkAllowWithActions,shouldAllowResendLinkPacket,initialResendLinkPacketAllowState,stepResendLinkPacketAllowWithActions,shouldAllowUpdateLinkKeepalive,initialUpdateLinkKeepaliveAllowState,stepUpdateLinkKeepaliveAllowWithActions,shouldAllowValidateLinkProof,initialValidateLinkProofAllowState,stepValidateLinkProofAllowWithActions,
  deriveRnsLinkKeyRawFromActions,encodeLinkMtuBytesRawFromActions,encodeLinkSignallingBytesRawFromActions,initialComputeKeepaliveState,initialIndexOfPendingLinkAppRequestState,initialDeliverPendingLinkAppResponseState,initialComputeLinkEstablishmentTimeoutState,initialComputeLinkMduState,initialComputeLinkRequestTimeoutState,initialComputeLinkRttSecondsState,initialContainsResourceHashState,initialLinkAppRequestInboundState,initialInvokeLinkAppRequestHandlerState,initialLinkEstablishState,initialLinkIdentifyState,initialCommitLinkRemoteIdentityState,initialLinkProofValidateState,initialLinkResourceAdvertisementState,initialLinkTeardownState,initialLinkTokenAccessState,initialLinkValidateRequestState,initialMergeLinkRttState,initialPendingLinkRequestRegisterState,initialRequestLinkDestinationState,initialSendLinkAppRequestResponseState,shouldTreatLinkClosed,initialLinkClosedState,stepLinkClosedWithActions,shouldMatchExpectedLinkMode,initialExpectedLinkModeState,stepExpectedLinkModeWithActions,shouldTreatLinkModeEnabled,initialLinkModeEnabledState,stepLinkModeEnabledWithActions,linkEstablishActivatedAction,linkEstablishmentTimeoutFromActions,linkIdentifySignedMaterialRawFromActions,linkKeepaliveFromActions,linkMduFromActions,linkProofSignedMaterialRawFromActions,shouldLinkReadyForNewResource,initialLinkReadyForNewResourceState,stepLinkReadyForNewResourceWithActions,linkRequestHashablePartRawFromActions,linkRequestTimeoutFromActions,linkRttSecondsFromActions,linkTeardownRemoteCloseAction,linkTeardownSendThenCloseAction,mergeLinkRttFromActions,modeFromLinkProofDataFromActions,
  modeFromLinkRequestDataFromActions,msgpackFloatFromActions,mtuFromLinkProofDataFromActions,mtuFromLinkRequestDataFromActions,packLinkKeepaliveProbeRawFromActions,packLinkKeepaliveReplyRawFromActions,packLinkIdentifyPayloadRawFromActions,packLinkProofDataRawFromActions,packLinkRequestDataRawFromActions,packMsgpackFloat64RawFromActions,initialClassifyLinkKeepaliveState,initialClassifyLinkProofPayloadState,initialEncodeLinkMtuBytesState,initialEncodeLinkSignallingBytesState,initialLinkProofSignedMaterialState,initialLinkRequestHashablePartState,initialModeFromLinkProofDataState,initialModeFromLinkRequestDataState,initialMtuFromLinkProofDataState,initialMtuFromLinkRequestDataState,initialLinkAppRequestState,initialLinkAppRequestTransmitState,initialLinkDataContextState,initialLinkHopsMatchState,initialLinkInitiatorMtuState,initialLinkRequestResponderMtuState,initialLinkResourceConcludeState,initialLinkIdentifySignedMaterialState,initialPackLinkIdentifyPayloadState,initialPackLinkKeepaliveProbeState,initialPackLinkKeepaliveReplyState,initialPackLinkProofDataState,initialPackLinkRequestDataState,initialPackLinkRequestState,initialPackLinkResponseState,initialPackMsgpackFloat64State,initialSplitLinkIdentifyPayloadState,initialSplitLinkProofBodyState,initialSplitLinkRequestDataState,initialUnpackLinkRequestState,initialUnpackLinkResponseState,initialUnpackMsgpackFloatState,linkIdentifyPayloadFieldsFromActions,linkInitiatorMtuFromActions,linkProofBodyFieldsFromActions,linkRequestFieldsFromActions,linkRequestKeyFieldsFromActions,linkRequestResponderMtuFromActions,
  linkResponseFieldsFromActions,packLinkRequestRawFromActions,packLinkResponseRawFromActions,shouldClassifyLinkKeepaliveProbe,shouldClassifyLinkProofPayloadBodyOnly,shouldClassifyLinkProofPayloadBodyWithMtu,shouldRejectMtuFromLinkProofData,shouldRejectMtuFromLinkRequestData,shouldRejectPackLinkIdentifyPayload,shouldRejectSplitLinkIdentifyPayload,shouldRejectSplitLinkProofBody,shouldRejectSplitLinkRequestData,shouldRejectUnpackLinkRequest,shouldRejectUnpackLinkResponse,shouldRejectUnpackMsgpackFloat,shouldUseEncodeLinkMtuBytes,shouldUseEncodeLinkSignallingBytes,shouldMatchLinkHops,shouldUseLinkEstablishmentTimeout,shouldUseLinkInitiatorMtu,shouldUseLinkKeepalive,shouldUseLinkMdu,shouldUseLinkProofSignedMaterial,shouldUseLinkRequestHashablePart,shouldUseLinkRequestResponderMtu,shouldUseLinkRequestTimeout,shouldUseLinkRttSeconds,shouldUseMergeLinkRtt,shouldUseModeFromLinkProofData,shouldUseModeFromLinkRequestData,shouldUseMtuFromLinkProofData,shouldUseMtuFromLinkRequestData,shouldUseLinkIdentifySignedMaterial,shouldUsePackLinkIdentifyPayload,shouldUsePackLinkKeepaliveProbe,shouldUsePackLinkKeepaliveReply,shouldUsePackLinkProofData,shouldUsePackLinkRequest,shouldUsePackLinkRequestData,shouldUsePackLinkResponse,shouldUsePackMsgpackFloat64,shouldUseSplitLinkIdentifyPayload,shouldUseSplitLinkProofBody,shouldUseSplitLinkRequestData,shouldUseUnpackLinkRequest,shouldUseUnpackLinkResponse,shouldUseUnpackMsgpackFloat,stepClassifyLinkKeepaliveWithActions,stepClassifyLinkProofPayloadWithActions,stepComputeKeepaliveWithActions,stepComputeLinkEstablishmentTimeoutWithActions,
  stepComputeLinkMduWithActions,stepComputeLinkRequestTimeoutWithActions,stepComputeLinkRttSecondsWithActions,stepEncodeLinkMtuBytesWithActions,stepEncodeLinkSignallingBytesWithActions,stepLinkProofSignedMaterialWithActions,stepLinkRequestHashablePartWithActions,stepMergeLinkRttWithActions,stepModeFromLinkProofDataWithActions,stepModeFromLinkRequestDataWithActions,stepMtuFromLinkProofDataWithActions,stepMtuFromLinkRequestDataWithActions,stepLinkHopsMatchWithActions,stepLinkInitiatorMtuWithActions,stepLinkRequestResponderMtuWithActions,stepLinkIdentifySignedMaterialWithActions,stepPackLinkIdentifyPayloadWithActions,stepPackLinkKeepaliveProbeWithActions,stepPackLinkKeepaliveReplyWithActions,stepPackLinkProofDataWithActions,stepPackLinkRequestDataWithActions,stepPackLinkRequestWithActions,stepPackLinkResponseWithActions,stepPackMsgpackFloat64WithActions,stepSplitLinkIdentifyPayloadWithActions,stepSplitLinkProofBodyWithActions,stepSplitLinkRequestDataWithActions,stepUnpackLinkRequestWithActions,stepIndexOfPendingLinkAppRequestWithActions,stepDeliverPendingLinkAppResponseWithActions,stepUnpackLinkResponseWithActions,stepUnpackMsgpackFloatWithActions,initialPendingLinkRequestUnregisterState,pendingLinkRequestUnregisterIndex,shouldAcceptLinkEstablishRtt,shouldAcceptLinkPacketInterfaceNow,initialAcceptLinkPacketInterfaceState,stepAcceptLinkPacketInterfaceWithActions,shouldAcceptLinkResourceAdvertisement,shouldAcceptRemoteLinkTeardown,shouldAcceptResourceHashmapUpdateFrameNow,shouldAcceptResourceProofPayloadNow,initialAcceptResourceProofPayloadState,
  stepAcceptResourceProofPayloadWithActions,shouldAcceptResourceProofSplitNow,initialAcceptResourceProofSplitState,stepAcceptResourceProofSplitWithActions,shouldActivateLinkEstablish,shouldAllowRequestLinkDestination,shouldAskAppLinkResourceAdvertisement,shouldAttemptLinkProofCryptoNow,initialAttemptLinkProofCryptoState,stepAttemptLinkProofCryptoWithActions,shouldCloseOnlyLinkTeardown,shouldCommitLinkIdentify,shouldCommitLinkRemoteIdentityNow,shouldContinueLinkValidateRequestNow,initialContinueLinkValidateRequestState,stepContinueLinkValidateRequestWithActions,shouldProceedLinkValidateRequest,shouldCreateLinkChannelNow,initialCreateLinkChannelState,stepCreateLinkChannelWithActions,shouldCreateLinkToken,shouldDispatchLinkPlaintextNow,initialDispatchLinkPlaintextState,stepDispatchLinkPlaintextWithActions,shouldUsePendingLinkAppRequestIndex,pendingLinkAppRequestIndexFromActions,shouldDeliverPendingLinkAppResponseNow,shouldEncryptLinkPayloadNow,initialEncryptLinkPayloadState,stepEncryptLinkPayloadWithActions,shouldEnterLinkHandshake,shouldFailLinkEstablish,shouldForbidLinkAppRequestInbound,shouldHandleIncomingResourceByHashNow,initialHandleIncomingResourceByHashState,stepHandleIncomingResourceByHashWithActions,shouldHandleOutgoingResourceRequestNow,initialHandleOutgoingResourceRequestState,stepHandleOutgoingResourceRequestWithActions,shouldIgnoreInitiatorKeepaliveProbeNow,initialIgnoreInitiatorKeepaliveProbeState,stepIgnoreInitiatorKeepaliveProbeWithActions,shouldIgnoreLinkAppRequestInbound,shouldIgnoreLinkAppRequestInboundResponse,shouldIgnoreLinkEstablishRtt,
  shouldHandleLinkDataChannel,shouldHandleLinkDataClose,shouldHandleLinkDataIdentify,shouldHandleLinkDataKeepalive,shouldHandleLinkDataPlaintext,shouldHandleLinkDataRequest,shouldHandleLinkDataResource,shouldHandleLinkDataResourceAdv,shouldHandleLinkDataResourceHmu,shouldHandleLinkDataResourceIcl,shouldHandleLinkDataResourceRcl,shouldHandleLinkDataResourceReq,shouldHandleLinkDataResponse,shouldHandleLinkDataRtt,shouldIgnoreLinkDataContext,shouldIgnoreLinkResourceAdvertisement,shouldInvokeLinkAppRequestHandlerNow,shouldInvokeLinkAppRequestInbound,shouldKeepPendingLinkAppRequestTransmit,shouldPresentResourceHash,shouldRegisterLinkResourceNow,initialRegisterLinkResourceState,stepRegisterLinkResourceWithActions,shouldRegisterPendingLinkRequestNow,shouldRejectLinkAppRequest,shouldRejectLinkAppRequestInboundTooBig,shouldRejectLinkIdentify,shouldRejectLinkProofValidate,shouldRejectLinkResourceAdvertisement,shouldRejectLinkTokenNoKey,shouldRemoveIncomingLinkResourceConclude,shouldRemoveOutgoingLinkResourceConclude,incomingLinkResourceConcludeIndex,outgoingLinkResourceConcludeIndex,shouldReplyKeepaliveProbeNow,initialReplyKeepaliveProbeState,stepReplyKeepaliveProbeWithActions,shouldReuseLinkToken,shouldSendLinkAppRequest,shouldSendLinkAppRequestInboundResponse,shouldSendLinkAppRequestResponseNow,shouldSendLinkTeardownThenClose,shouldTeardownLinkEstablish,shouldUnregisterLinkAppRequestTransmit,shouldRemovePendingLinkRequest,shouldUpdateLinkLastDataNow,initialUpdateLinkLastDataState,stepUpdateLinkLastDataWithActions,shouldDispatchLinkInboundData,initialLinkInboundDataPacketState,
  stepLinkInboundDataPacketWithActions,identityPublicKeyFieldsFromActions,initialLinkKeepaliveContextState,initialSplitIdentityPublicKeyState,initialDeriveRnsLinkKeyState,initialSplitInitiatorLinkEntropyState,initialSplitResponderLinkEntropyState,initiatorLinkEntropyFieldsFromActions,responderLinkEntropyFieldsFromActions,shouldRejectDeriveRnsLinkKey,shouldRejectSplitInitiatorLinkEntropy,shouldUseDeriveRnsLinkKey,shouldRejectSplitResponderLinkEntropy,shouldTreatLinkKeepaliveContext,shouldTreatLinkKeepaliveOther,shouldUseSplitIdentityPublicKey,shouldUseSplitInitiatorLinkEntropy,shouldUseSplitResponderLinkEntropy,stepLinkKeepaliveContextWithActions,stepSplitIdentityPublicKeyWithActions,stepDeriveRnsLinkKeyWithActions,stepSplitInitiatorLinkEntropyWithActions,stepSplitResponderLinkEntropyWithActions,initialSplitResourceHashmapUpdatePacketState,initialAcceptResourceHashmapUpdateFrameState,initialSplitResourceProofState,resourceHashmapUpdatePacketFieldsFromActions,resourceProofFieldsFromActions,shouldRejectSplitResourceHashmapUpdatePacket,shouldRejectSplitResourceProof,shouldUseSplitResourceHashmapUpdatePacket,shouldUseSplitResourceProof,stepLinkAppRequestInboundWithActions,stepLinkAppRequestTransmitWithActions,stepLinkAppRequestWithActions,stepInvokeLinkAppRequestHandlerWithActions,stepSendLinkAppRequestResponseWithActions,stepLinkDataContextWithActions,stepLinkEstablishWithActions,stepLinkIdentifyWithActions,stepCommitLinkRemoteIdentityWithActions,stepLinkProofValidateWithActions,stepLinkResourceAdvertisementWithActions,stepContainsResourceHashWithActions,
  stepLinkResourceConcludeWithActions,stepPendingLinkRequestRegisterWithActions,stepPendingLinkRequestUnregisterWithActions,stepRequestLinkDestinationWithActions,stepLinkTeardownWithActions,stepLinkTokenAccessWithActions,stepLinkValidateRequestWithActions,stepLinkWatchdogWithActions,stepSplitResourceHashmapUpdatePacketWithActions,stepAcceptResourceHashmapUpdateFrameWithActions,stepSplitResourceProofWithActions,stepUtf8EncodeWithActions,initialUtf8EncodeState,shouldUseUtf8Encode,utf8EncodeRawFromActions,type LinkAppRequestInboundAction,type LinkAppRequestInboundState,type LinkEstablishAction,type LinkIdentifyAction,type LinkModeValue,type LinkRequestFields,type LinkResourceAdvertisementAction,type LinkResourceAdvertisementState,type LinkResourceStrategyValue,type LinkStatusValue,type LinkTeardownAction,type LinkTeardownReasonValue,type LinkWatchdogState,type LinkWatchdogStepResult } from "@twistedpear/protocol";
import type { CryptoProvider } from "../crypto/provider.js";
import { Token } from "../crypto/token.js";
import { Channel,LinkChannelOutlet } from "../channel.js";
import { equalBytes } from "../crypto/bytes.js";
import { DestinationDirection,DestinationType } from "../destination.js";
import { Identity } from "../identity.js";
import type { PacketInterface } from "../interfaces/interface.js";
import { LinkRequestReceipt } from "../link-request-receipt.js";
import { Packet,PacketContext,PacketHeaderType,PacketType,TransportType } from "../packet.js";
import type { PacketReceipt } from "../packet-receipt.js";
import type { RegisteredDestination,RequestHandler } from "../registered-destination.js";
import { RETICULUM_MTU } from "../reticulum.js";
import type { Clock } from "../runtime/runtime.js";
import type { LeafTransport } from "../transport/node.js";
import { PATHFINDER_MAX_HOPS } from "../transport/node.js";
import { Resource,ResourceAdvertisement } from "../resource.js";
import type { Link } from "../link.js";
/** Mirrors RNS/Link.py link mode constants (RNS 0.9.4). */
export {
  LinkMode,
  LINK_MODE_DEFAULT,
  LINK_ENABLED_MODES,
  LINK_MTU_BYTEMASK,
  LINK_MODE_BYTEMASK,
  type LinkModeValue
};

/** Mirrors RNS/Link.py constants (RNS 0.9.4). */
export const LINK_ECPUB_SIZE = LINK_REQUEST_ECPUB_SIZE;
export const LINK_KEY_SIZE = LINK_X25519_KEY_SIZE;
export const LINK_MTU_SIZE = LINK_PROOF_MTU_SIZE;
export const LINK_SIGNATURE_SIZE = LINK_PROOF_SIGNATURE_SIZE;
export {
  LINK_KEEPALIVE,
  LINK_KEEPALIVE_MIN,
  LINK_KEEPALIVE_MAX_RTT,
  LINK_STALE_FACTOR,
  LINK_STALE_GRACE,
  LINK_TRAFFIC_TIMEOUT_FACTOR,
  LINK_KEEPALIVE_TIMEOUT_FACTOR,
  LINK_WATCHDOG_MAX_SLEEP_MS,
  LINK_ESTABLISHMENT_TIMEOUT_PER_HOP,
  LINK_RESPONSE_MAX_GRACE_TIME,
  LinkStatus,
  LinkTeardownReason,
  LinkResourceStrategy,
  type LinkStatusValue,
  type LinkTeardownReasonValue,
  type LinkResourceStrategyValue
};

export interface LinkCallbacks {
  linkEstablished?: (link: Link) => void;
  linkClosed?: (link: Link) => void;
  packet?: (data: Uint8Array, packet: Packet) => void;
  remoteIdentified?: (link: Link, identity: Identity) => void;
  resource?: (advertisement: ResourceAdvertisement) => boolean;
  resourceConcluded?: (resource: Resource) => void;
}

export interface InitiatorLinkOptions {
  readonly destination: RegisteredDestination;
  readonly transport: LeafTransport;
  readonly linkMtuDiscovery?: boolean;
  readonly callbacks?: LinkCallbacks;
  /**
   * Optional injected entropy for initiator X25519 + Ed25519 private keys
   * (64 bytes). When omitted, the crypto provider supplies randomness.
   */
  readonly entropy?: Uint8Array;
}

export interface LinkRequestOptions {
  readonly response?: (receipt: LinkRequestReceipt) => void;
  readonly failed?: (receipt: LinkRequestReceipt) => void;
  readonly timeout?: number;
}

export interface LinkSendContextResult {
  readonly raw: Uint8Array;
  readonly receipt: PacketReceipt | null;
}

export function linkEstablishmentTimeoutForHops(hops: number, keepalive = LINK_KEEPALIVE): number {
  const stepped = stepComputeLinkEstablishmentTimeoutWithActions(
    initialComputeLinkEstablishmentTimeoutState(),
    {
      kind: "link/establishment-timeout-gate",
      hops,
      keepalive
    }
  );
  const timeout = shouldUseLinkEstablishmentTimeout(stepped.actions)
    ? linkEstablishmentTimeoutFromActions(stepped.actions)
    : null;
  if (timeout === null) {
    throw new Error("Link: missing use-timeout action for establishment timeout");
  }
  return timeout;
}

export function linkRttSecondsForRequest(nowSeconds: number, requestTimeSeconds: number): number {
  const stepped = stepComputeLinkRttSecondsWithActions(initialComputeLinkRttSecondsState(), {
    kind: "link/rtt-seconds-gate",
    nowSeconds,
    requestTimeSeconds
  });
  const rtt = shouldUseLinkRttSeconds(stepped.actions)
    ? linkRttSecondsFromActions(stepped.actions)
    : null;
  if (rtt === null) {
    throw new Error("Link: missing use-rtt action for RTT seconds");
  }
  return rtt;
}

export function mergedLinkRtt(measuredSeconds: number, remoteSeconds: number): number {
  const stepped = stepMergeLinkRttWithActions(initialMergeLinkRttState(), {
    kind: "link/merge-rtt-gate",
    measuredSeconds,
    remoteSeconds
  });
  const rtt = shouldUseMergeLinkRtt(stepped.actions)
    ? mergeLinkRttFromActions(stepped.actions)
    : null;
  if (rtt === null) {
    throw new Error("Link: missing use-rtt action for merged RTT");
  }
  return rtt;
}

export function linkRequestTimeoutForRtt(rtt: number): number {
  const stepped = stepComputeLinkRequestTimeoutWithActions(
    initialComputeLinkRequestTimeoutState(),
    {
      kind: "link/request-timeout-gate",
      rtt
    }
  );
  const timeout = shouldUseLinkRequestTimeout(stepped.actions)
    ? linkRequestTimeoutFromActions(stepped.actions)
    : null;
  if (timeout === null) {
    throw new Error("Link: missing use-timeout action for request timeout");
  }
  return timeout;
}

export function linkMduForMtu(mtu: number): number {
  const stepped = stepComputeLinkMduWithActions(initialComputeLinkMduState(), {
    kind: "link/mdu-gate",
    mtu
  });
  const mdu = shouldUseLinkMdu(stepped.actions) ? linkMduFromActions(stepped.actions) : null;
  if (mdu === null) {
    throw new Error("Link: missing use-mdu action");
  }
  return mdu;
}
