#!/usr/bin/env node
/**
 * Pack chat example and bundle the W3 browser distribution spike for Playwright.
 */

import { cpSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { buildSync } from "esbuild";
import { encode256t, verify256t } from "../../packages/cas-256t/dist/index.js";
import { verifyPackage } from "../../packages/app-registry/dist/index.js";
import { NodeCryptoProvider } from "../../packages/reticulum-ts/dist/index.js";
import { decryptIdentityBackup } from "../../packages/host-core/dist/index.js";
import { runInit, runPack } from "../../packages/cli/dist/commands/index.js";

const distributionRoot = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(distributionRoot, "../..");
const harnessRoot = join(repoRoot, "apps/harness-mobile");
const chatDir = resolve(distributionRoot, "../../apps/examples/chat");
const IDENTITY_PASSPHRASE = "conformance identity passphrase";

function bytesToHex(bytes) {
  return Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join("");
}

async function packChatFixture() {
  const cwd = mkdtempSync(join(tmpdir(), "tp-web-distribution-chat-"));
  const appDir = join(cwd, "chat");
  cpSync(chatDir, appDir, { recursive: true });

  try {
    const initCode = await runInit({ cwd, identityPassphrase: IDENTITY_PASSPHRASE, args: [] });
    if (initCode !== 0) {
      throw new Error("tp init failed for chat");
    }

    const packCode = await runPack({ cwd, args: ["chat", "--out", "chat.tpkg"] });
    if (packCode !== 0) {
      throw new Error("tp pack failed for chat");
    }

    const provider = new NodeCryptoProvider();
    const identity = decryptIdentityBackup(
      provider,
      new Uint8Array(readFileSync(join(cwd, ".tp/identity"))),
      IDENTITY_PASSPHRASE
    );
    const privateKeyHex = bytesToHex(identity.getPrivateKey());

    const archive = new Uint8Array(readFileSync(join(cwd, "chat.tpkg")));
    const verified = verifyPackage(provider, archive, { hostApiVersion: "0.1.0" });
    const t256 = encode256t(archive, (data) => provider.sha512(data));
    if (!verify256t(t256, archive, (data) => provider.sha512(data))) {
      throw new Error("256t id does not verify against archive");
    }

    return {
      appId: verified.manifest.name,
      version: verified.manifest.version,
      capabilities: verified.manifest.capabilities ?? [],
      publisherPublicKey: verified.manifest.publisherPublicKey,
      privateKeyHex,
      archiveHex: bytesToHex(archive),
      t256,
      archiveBytes: archive.length
    };
  } finally {
    rmSync(cwd, { recursive: true, force: true });
  }
}

function hexToBytes(hex) {
  const bytes = new Uint8Array(hex.length / 2);
  for (let index = 0; index < bytes.length; index += 1) {
    bytes[index] = Number.parseInt(hex.slice(index * 2, index * 2 + 2), 16);
  }

  return bytes;
}

const build = spawnSync(
  "npm",
  [
    "run",
    "build",
    "--workspace=@twistedpear/miniapp-runtime",
    "--workspace=@twistedpear/host-core",
    "--workspace=@twistedpear/reticulum-ts",
    "--workspace=@twistedpear/app-registry",
    "--workspace=@twistedpear/cas-256t",
    "--workspace=@twistedpear/bridge-hyper",
    "--workspace=@twistedpear/cli"
  ],
  { cwd: repoRoot, stdio: "inherit" }
);
if (build.status !== 0) {
  process.exit(build.status ?? 1);
}

const workerBuild = spawnSync("node", ["scripts/build-web-worker.mjs"], {
  cwd: harnessRoot,
  stdio: "inherit"
});
if (workerBuild.status !== 0) {
  process.exit(workerBuild.status ?? 1);
}

const fixture = await packChatFixture();
console.log(`web-distribution: packed chat (${fixture.archiveBytes} bytes) t256=${fixture.t256.slice(0, 16)}…`);

writeFileSync(
  join(distributionRoot, "fixtures.mjs"),
  `/** Generated by conformance/web-distribution/build.mjs — do not edit. */\nexport const DISTRIBUTION_FIXTURE = ${JSON.stringify(
    {
      appId: fixture.appId,
      version: fixture.version,
      capabilities: fixture.capabilities,
      publisherPublicKey: fixture.publisherPublicKey,
      t256: fixture.t256
    },
    null,
    2
  )};\n`
);

writeFileSync(
  join(distributionRoot, "publisher-data.mjs"),
  `/** Generated by conformance/web-distribution/build.mjs — do not edit. */\nexport const PUBLISHER_DATA = ${JSON.stringify(
    {
      privateKeyHex: fixture.privateKeyHex,
      archiveHex: fixture.archiveHex,
      t256: fixture.t256,
      appId: fixture.appId,
      version: fixture.version,
      packageHash: verifyPackage(new NodeCryptoProvider(), hexToBytes(fixture.archiveHex), {
        hostApiVersion: "0.1.0"
      }).packageHash
    },
    null,
    2
  )};\n`
);

buildSync({
  entryPoints: [join(distributionRoot, "entry.mjs")],
  bundle: true,
  platform: "browser",
  format: "esm",
  outfile: join(distributionRoot, "distribution.bundle.js"),
  logLevel: "warning"
});

writeFileSync(
  join(distributionRoot, "web-core.worker.js"),
  readFileSync(join(harnessRoot, "public/web-core.worker.js"), "utf8")
);

console.log("web-distribution bundle written");
