apply plugin: 'com.android.library'
apply plugin: 'expo-module-gradle-plugin'
apply from: new File(rootProject.rootDir, '../../../conformance/android-native/jacoco-module.gradle')

group = 'network.twistedpear.harness'
version = '0.0.0'

android {
  namespace "expo.modules.twistedpear.multicast"
  defaultConfig {
    versionCode 1
    versionName "0.0.0"
  }
}

dependencies {
  testImplementation "junit:junit:4.13.2"
}
