apply plugin: 'com.android.library'

group = 'network.twistedpear.harness'
version = '0.0.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useDefaultAndroidSdkVersions()
useExpoPublishing()

android {
  namespace "expo.modules.twistedpear.multicast"
  defaultConfig {
    versionCode 1
    versionName "0.0.0"
  }
}

dependencies {
  testImplementation "junit:junit:4.13.2"
}
