// Generated by scripts/generate-capability-risk.mjs — do not edit.
// Source: specs/spec-cap/registry/capability-risk.json

export type CapabilityRiskClass = "benign" | "elevated" | "sensitive" | "critical";

export interface CapabilityRiskEntry {
  readonly id: string;
  readonly riskClass: CapabilityRiskClass;
  readonly namesDestination: boolean;
  readonly irreversibleOrThirdParty: boolean;
  readonly readsSensorSecretOrForeignData: boolean;
  readonly standing: boolean;
}

export const CAPABILITY_RISK_HOST_API = "0.14.0" as const;

export const CAPABILITY_RISK_REGISTRY: ReadonlyArray<CapabilityRiskEntry> = [
  {
    "id": "identity",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "presence",
    "riskClass": "benign",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "announce:subscribe",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "announce:publish",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "lxmf:send",
    "riskClass": "sensitive",
    "namesDestination": true,
    "irreversibleOrThirdParty": true,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "lxmf:receive",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "storage:kv",
    "riskClass": "benign",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "storage:hyperbee",
    "riskClass": "benign",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "resource:fetch",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "workspace",
    "riskClass": "benign",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "ai:chat",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "ai:embed",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "apps:package",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": true,
    "readsSensorSecretOrForeignData": false,
    "standing": false
  },
  {
    "id": "apps:publish",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": true,
    "readsSensorSecretOrForeignData": false,
    "standing": false
  },
  {
    "id": "apps:install",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": true,
    "readsSensorSecretOrForeignData": false,
    "standing": false
  },
  {
    "id": "apps:preview",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": false
  },
  {
    "id": "apps:channel",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": false
  },
  {
    "id": "runtime:background",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "runtime:wake",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "notify:post",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "share:cas",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "peer:connect",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "link:observe",
    "riskClass": "benign",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "link:probe",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "relay:configure",
    "riskClass": "critical",
    "namesDestination": false,
    "irreversibleOrThirdParty": true,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "relay:read",
    "riskClass": "benign",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "freenet:contract",
    "riskClass": "sensitive",
    "namesDestination": true,
    "irreversibleOrThirdParty": true,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "device:location",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:location:precise",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:ambient-light",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:camera",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:camera:frames",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:microphone",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:microphone:pcm",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:motion",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:motion:samples",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:torch",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "device:speaker",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "device:speaker:pcm",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "device:tts",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "device:stt",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:haptics",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "device:battery",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:screen-capture",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:screen-capture:frames",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:nfc",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:nfc:apdu",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:biometric",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:proximity",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:barometer",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:thermometer",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:hygrometer",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:thermal",
    "riskClass": "elevated",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  },
  {
    "id": "device:stream",
    "riskClass": "sensitive",
    "namesDestination": true,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "device:remote",
    "riskClass": "sensitive",
    "namesDestination": true,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "device:share-policy:read",
    "riskClass": "benign",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": false,
    "standing": true
  },
  {
    "id": "device:stream:raw-inbound",
    "riskClass": "sensitive",
    "namesDestination": false,
    "irreversibleOrThirdParty": false,
    "readsSensorSecretOrForeignData": true,
    "standing": true
  }
] as const;

const CAPABILITY_RISK_BY_ID = new Map(
  CAPABILITY_RISK_REGISTRY.map((entry) => [entry.id, entry]),
);

export function capabilityRiskById(id: string): CapabilityRiskEntry | undefined {
  return CAPABILITY_RISK_BY_ID.get(id);
}

export function riskClassForCapability(id: string): CapabilityRiskClass {
  const entry = capabilityRiskById(id);
  if (entry === undefined) {
    throw new Error(`unknown capability risk id: ${id}`);
  }
  return entry.riskClass;
}
