#!/usr/bin/env node
/**
 * Read stores this project wrote earlier, with the build of today.
 *
 * The wire formats are covered from several directions — golden vectors,
 * property tests, fuzzing, and differential fuzzing against a pinned reference.
 * The formats *at rest* had none of that. `migrateLegacyGrantRecord` and the
 * unencrypted-identity path in `host-core` are both migration code with no test
 * that starts from a file an older host actually left behind; every existing
 * test encodes with today's encoder and decodes with today's decoder, which
 * passes just as happily after a breaking change to both halves.
 *
 * This is the axis where that matters most. TwistedPear is local-first: a
 * user's grants, identity, block list, and half-finished transfers live on
 * their device, and there is no server to re-read them from. A format change
 * that silently fails to load is not a bug report, it is a person whose
 * identity is gone.
 *
 * So: `fixtures/` holds committed bytes, `fixtures/expected.json` holds what
 * they mean, and this asserts the current build still gets from one to the
 * other. The fixtures are never regenerated by a gate — see `record.mjs`.
 *
 * Usage: node conformance/state-migration/run.mjs [--write]
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { formats, fixtureBytes } from "./formats.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const FIXTURES = path.join(HERE, "fixtures");
const EXPECTED = path.join(FIXTURES, "expected.json");
const write = process.argv.includes("--write");

const readJson = (file, fallback) =>
  existsSync(file) ? JSON.parse(readFileSync(file, "utf8")) : fallback;

const recorded = readJson(EXPECTED, { formats: {} });
const findings = [];
const results = {};

for (const format of formats) {
  const file = path.join(FIXTURES, format.file);
  if (!existsSync(file)) {
    findings.push(
      `${format.id}: no fixture at ${path.relative(ROOT, file)}. Run node conformance/state-migration/record.mjs.`,
    );
    continue;
  }
  try {
    results[format.id] = format.read(fixtureBytes(file), file);
  } catch (error) {
    findings.push(
      `${format.id}: the current build cannot read a store it wrote earlier — ${error.message}`,
    );
  }
}

if (write) {
  if (findings.length > 0) {
    for (const finding of findings) console.error(`  ${finding}`);
    console.error(
      "\nRefusing to record expectations while a fixture fails to read; that would freeze the failure as the expectation.",
    );
    process.exit(1);
  }
  mkdirSync(FIXTURES, { recursive: true });
  writeFileSync(
    EXPECTED,
    `${JSON.stringify(
      {
        version: 1,
        description:
          "What each committed store fixture means, as read by the build that recorded it. The fixtures are the input and this is the answer; a change to either is a change to what users' existing data decodes to.",
        formats: results,
      },
      null,
      2,
    )}\n`,
  );
  console.log(
    `state-migration: recorded expectations for ${Object.keys(results).length} format(s).`,
  );
  process.exit(0);
}

for (const format of formats) {
  const expected = recorded.formats?.[format.id];
  const actual = results[format.id];
  if (actual === undefined) continue;
  if (expected === undefined) {
    findings.push(
      `${format.id}: read cleanly but has no recorded expectation. Run run.mjs --write.`,
    );
    continue;
  }
  const [left, right] = [JSON.stringify(expected), JSON.stringify(actual)];
  if (left !== right)
    findings.push(
      `${format.id}: decodes to something else now.\n      was: ${left}\n      now: ${right}`,
    );
}

// A format that quietly stops being covered is the same failure one level up:
// deleting an entry from `formats.mjs` would drop its fixture from the run and
// leave every remaining check green.
for (const id of Object.keys(recorded.formats ?? {}))
  if (!formats.some((format) => format.id === id))
    findings.push(
      `${id}: has a recorded expectation but is no longer in formats.mjs. A persisted format does not stop mattering because the code stopped reading it — users still have the file.`,
    );

for (const finding of findings) console.error(`  ${finding}`);
console.log(
  `state-migration: ${findings.length === 0 ? "PASS" : "FAIL"}; ${Object.keys(results).length}/${formats.length} format(s) read, ${findings.length} finding(s).`,
);
process.exit(findings.length === 0 ? 0 : 1);
