#!/usr/bin/env node
/**
 * Pack signed DevStudio and bundle the W3 browser DevStudio spike for Playwright.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawnSync } from "node:child_process";
import { buildSync } from "esbuild";
import {
  buildUnsignedManifest,
  packPackage,
  signManifest,
  verifyPackage,
} from "../../packages/app-registry/dist/index.js";
import {
  Identity,
  NodeCryptoProvider,
} from "../../packages/reticulum-ts/dist/index.js";
import { HOST_API_VERSION } from "../../packages/miniapp-runtime/dist/host-api.js";

const devstudioRoot = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(devstudioRoot, "../..");
const harnessRoot = join(repoRoot, "apps/harness-mobile");
const devstudioDir = join(repoRoot, "apps/devstudio");

function bytesToHex(bytes) {
  return Array.from(bytes, (value) => value.toString(16).padStart(2, "0")).join(
    "",
  );
}

async function packDevstudioFixture() {
  const provider = new NodeCryptoProvider();
  const identity = new Identity(provider);
  const privateKeyHex = bytesToHex(identity.getPrivateKey());
  const devstudioManifest = JSON.parse(
    readFileSync(join(devstudioDir, "app.manifest.json"), "utf8"),
  );
  const devstudioFiles = [
    {
      path: "bundle.js",
      content: new Uint8Array(readFileSync(join(devstudioDir, "bundle.js"))),
    },
  ];
  const unsigned = buildUnsignedManifest(
    {
      name: devstudioManifest.name,
      version: devstudioManifest.version,
      entry: devstudioManifest.entry,
      capabilities: devstudioManifest.capabilities,
      icon: null,
      minHostApi: devstudioManifest.minHostApi,
      driveKey: "0".repeat(64),
      publisherPublicKey: bytesToHex(identity.getPublicKey()),
      files: devstudioFiles,
    },
    provider,
  );
  const signedManifest = signManifest(provider, identity, unsigned);
  const packed = packPackage(provider, {
    ...signedManifest,
    signature: signedManifest.signature,
    files: devstudioFiles,
  });
  const verified = verifyPackage(provider, packed.archiveBytes, {
    hostApiVersion: HOST_API_VERSION,
  });

  return {
    appId: verified.manifest.name,
    version: verified.manifest.version,
    capabilities: verified.manifest.capabilities ?? [],
    publisherPublicKey: verified.manifest.publisherPublicKey,
    privateKeyHex,
    archiveHex: bytesToHex(packed.archiveBytes),
    archiveBytes: packed.archiveBytes.length,
  };
}

const build = spawnSync(
  "npm",
  [
    "run",
    "build",
    "--workspace=@twistedpear/miniapp-runtime",
    "--workspace=@twistedpear/host-core",
    "--workspace=@twistedpear/reticulum-ts",
    "--workspace=@twistedpear/app-registry",
    "--workspace=@twistedpear/cas-256t",
    "--workspace=@twistedpear/bridge-hyper",
  ],
  { cwd: repoRoot, stdio: "inherit" },
);
if (build.status !== 0) {
  process.exit(build.status ?? 1);
}

const workerBuild = spawnSync("node", ["scripts/build-web-worker.mjs"], {
  cwd: harnessRoot,
  stdio: "inherit",
});
if (workerBuild.status !== 0) {
  process.exit(workerBuild.status ?? 1);
}

const fixture = await packDevstudioFixture();
console.log(`web-devstudio: packed devstudio (${fixture.archiveBytes} bytes)`);

writeFileSync(
  join(devstudioRoot, "fixtures.mjs"),
  `/** Generated by conformance/web-devstudio/build.mjs — do not edit. */\nexport const DEVSTUDIO_FIXTURE = ${JSON.stringify(fixture, null, 2)};\n`,
);

buildSync({
  entryPoints: [join(devstudioRoot, "entry.mjs")],
  bundle: true,
  platform: "browser",
  format: "esm",
  outfile: join(devstudioRoot, "devstudio.bundle.js"),
  logLevel: "warning",
});

writeFileSync(
  join(devstudioRoot, "web-core.worker.js"),
  readFileSync(join(harnessRoot, "public/web-core.worker.js"), "utf8"),
);

console.log("web-devstudio bundle written");
