import { describe, expect, it } from "vitest";
import {
  changedPaths,
  GENERATED_OUTPUTS,
} from "../../scripts/analysis/generated-freshness.mjs";

describe("generated freshness", () => {
  it("covers schema outputs and both shipping worklet bundles", () => {
    expect(GENERATED_OUTPUTS).toEqual(
      expect.arrayContaining([
        "packages/effects/src/types.gen.ts",
        "packages/protocol/src/device-registry.gen.ts",
        "packages/protocol/src/capability-risk.gen.ts",
        "packages/miniapp-runtime/src/device-capabilities.gen.ts",
        "apps/harness-mobile/worklet/worklet.bundle.mjs",
        "apps/host-desktop/worklet/worklet.bundle",
      ]),
    );
  });

  it("reports only outputs whose regenerated bytes differ", () => {
    const before = new Map([
      ["same", Buffer.from("a")],
      ["changed", Buffer.from("b")],
    ]);
    const after = new Map([
      ["same", Buffer.from("a")],
      ["changed", Buffer.from("c")],
    ]);
    expect(changedPaths(before, after)).toEqual(["changed"]);
  });
});
