apply plugin: 'jacoco'

jacoco {
  toolVersion = '0.8.13'
}

android {
  testOptions {
    unitTests.all {
      jacoco.includeNoLocationClasses = true
      jacoco.excludes = ['jdk.internal.*']
    }
  }
}

tasks.register('jacocoTestReport', JacocoReport) {
  dependsOn 'testDebugUnitTest'
  reports {
    xml.required = true
    html.required = false
    csv.required = false
  }
  sourceDirectories.setFrom(files('src/main/java'))
  classDirectories.setFrom(files(
    fileTree(dir: "$buildDir/tmp/kotlin-classes/debug", exclude: [
      '**/BuildConfig.*',
      '**/*Module*.*',
      '**/*Package*.*',
    ]),
    fileTree(dir: "$buildDir/intermediates/javac/debug/classes", exclude: [
      '**/BuildConfig.*',
      '**/*Module*.*',
      '**/*Package*.*',
    ]),
  ))
  executionData.setFrom(fileTree(dir: buildDir, include: [
    'jacoco/testDebugUnitTest.exec',
    'outputs/unit_test_code_coverage/debugUnitTest/testDebugUnitTest.exec',
  ]))
}
