#!/usr/bin/env node
/**
 * Seed a temporary Date.now() violation in the protocol package and verify that
 * the independent Sans-IO enforcement layers catch it. The fixture and the
 * baseline inventory report are restored before this process exits.
 */
import fs from "node:fs";
import path from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_REL = "packages/protocol/src/__sansio_canary__.ts";
const TEST_REL = "packages/protocol/test/__sansio_canary__.test.ts";
const SOURCE_PATH = path.join(ROOT, SOURCE_REL);
const TEST_PATH = path.join(ROOT, TEST_REL);
const INVENTORY_PATH = path.join(ROOT, "violations.json");
const REPORT_PATH = path.join(ROOT, "sansio-canary.json");
const MINIMUM_CATCHES = 3;

const source = `// Temporary fixture generated by scripts/sansio-canary.mjs.\nexport function runSansioCanary(): number {\n  return Date.now();\n}\n`;
const test = `import { expect, it } from "vitest";\nimport { SansIOViolation } from "@twistedpear/effects/tripwire";\nimport { runSansioCanary } from "../src/__sansio_canary__.js";\n\nit("catches a seeded Date.now call at runtime", () => {\n  expect(() => runSansioCanary()).toThrow(SansIOViolation);\n});\n`;

function run(command, args) {
  return spawnSync(command, args, {
    cwd: ROOT,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "pipe"],
  });
}

function commandOutput(result) {
  return `${result.stdout ?? ""}${result.stderr ?? ""}`.trim();
}

function restoreFile(file, previous) {
  if (previous === undefined) {
    fs.rmSync(file, { force: true });
  } else {
    fs.writeFileSync(file, previous);
  }
}

function isRestored(file, previous) {
  return previous === undefined
    ? !fs.existsSync(file)
    : fs.existsSync(file) && fs.readFileSync(file).equals(previous);
}

const previousSource = fs.existsSync(SOURCE_PATH)
  ? fs.readFileSync(SOURCE_PATH)
  : undefined;
const previousTest = fs.existsSync(TEST_PATH)
  ? fs.readFileSync(TEST_PATH)
  : undefined;
const previousInventory = fs.existsSync(INVENTORY_PATH)
  ? fs.readFileSync(INVENTORY_PATH)
  : undefined;

const layers = [];
let fatalError;

try {
  fs.writeFileSync(SOURCE_PATH, source);
  fs.writeFileSync(TEST_PATH, test);

  const eslint = run(path.join(ROOT, "node_modules/.bin/eslint"), [
    "--no-inline-config",
    "--max-warnings",
    "0",
    SOURCE_REL,
  ]);
  layers.push({
    name: "eslint",
    command: `eslint --no-inline-config --max-warnings 0 ${SOURCE_REL}`,
    caught:
      eslint.status !== 0 &&
      /Date\.now|no-restricted-syntax/.test(commandOutput(eslint)),
    evidence:
      commandOutput(eslint)
        .split("\n")
        .find((line) => /Date\.now|no-restricted-syntax/.test(line)) ??
      `exit ${eslint.status ?? "unknown"}`,
  });

  const inventory = run(process.execPath, [
    path.join(ROOT, "scripts/sansio-inventory.mjs"),
  ]);
  let inventoryReport;
  if (inventory.status === 0 && fs.existsSync(INVENTORY_PATH)) {
    inventoryReport = JSON.parse(fs.readFileSync(INVENTORY_PATH, "utf8"));
  }
  const inventoryViolation = inventoryReport?.violations?.find(
    (violation) =>
      violation.file === SOURCE_REL && violation.api === "Date.now",
  );
  layers.push({
    name: "ratchet-inventory",
    command: "node scripts/sansio-inventory.mjs",
    caught: inventoryViolation !== undefined,
    evidence:
      inventoryViolation === undefined
        ? commandOutput(inventory) || `exit ${inventory.status ?? "unknown"}`
        : `${inventoryViolation.file}:${inventoryViolation.line} ${inventoryViolation.api}`,
  });

  const tripwire = run(path.join(ROOT, "node_modules/.bin/vitest"), [
    "run",
    "--project",
    "protocol-tripwire",
    TEST_REL,
  ]);
  layers.push({
    name: "tripwire",
    command: `vitest run --project protocol-tripwire ${TEST_REL}`,
    caught: tripwire.status === 0,
    evidence:
      tripwire.status === 0
        ? "protocol test observed SansIOViolation from Date.now"
        : commandOutput(tripwire).slice(-1000),
  });
} catch (error) {
  fatalError = error;
} finally {
  restoreFile(SOURCE_PATH, previousSource);
  restoreFile(TEST_PATH, previousTest);
  restoreFile(INVENTORY_PATH, previousInventory);
}

const caughtCount = layers.filter((layer) => layer.caught).length;
const report = {
  generatedAt: new Date().toISOString(),
  canary: "temporary Date.now() call in a protocol source file",
  fixture: SOURCE_REL,
  minimumIndependentLayers: MINIMUM_CATCHES,
  caughtCount,
  passed: fatalError === undefined && caughtCount >= MINIMUM_CATCHES,
  layers,
  cleanup: {
    fixtureRestored: isRestored(SOURCE_PATH, previousSource),
    testRestored: isRestored(TEST_PATH, previousTest),
    inventoryRestored: isRestored(INVENTORY_PATH, previousInventory),
  },
};

fs.writeFileSync(REPORT_PATH, `${JSON.stringify(report, null, 2)}\n`);

if (fatalError !== undefined) {
  console.error(fatalError);
}
for (const layer of layers) {
  console.log(`Canary ${layer.name}: ${layer.caught ? "caught" : "MISSED"}`);
}
console.log(
  `Canary result: ${caughtCount}/${MINIMUM_CATCHES} required layers caught Date.now()`,
);

if (!report.passed || !Object.values(report.cleanup).every(Boolean)) {
  process.exit(1);
}
