export {
  DEVICE_CLASS_REGISTRY,
  DEVICE_REGISTRY_HOST_API,
  defaultTierForClass,
  deviceCapabilityId,
  deviceClassById,
  type DeviceBandwidthProfile,
  type DeviceEncodingBandwidthProfile,
  type DeviceClassDefaults,
  type DeviceClassEntry,
  type DeviceConsentClass,
  type DeviceRole,
  type DeviceTierDefinition,
} from "../device-registry.gen.js";
export {
  deviceSessionMachine,
  initialDeviceSessionState,
  isDeviceSessionLive,
  stepDeviceSession,
  type DeviceSessionEvent,
  type DeviceSessionPhase,
  type DeviceSessionState,
} from "../device-session.js";
export {
  quantizeAmbientLux,
  quantizeLocationCoarse,
  type AmbientLuxBucket,
  type CoarseLocationFix,
  type PreciseLocationFix,
} from "../device-quantize.js";
export {
  deriveCameraSample,
  deriveMicrophoneSample,
  deriveMotionSample,
  type CameraDerivedInput,
  type CameraDerivedSample,
  type MicrophoneDerivedInput,
  type MicrophoneDerivedSample,
  type MotionDerivedSample,
  type RawMotionSample,
} from "../device-processors.js";
export {
  ActuatorSafetyError,
  HAPTICS_MAX_DUTY_CYCLE,
  HAPTICS_MAX_PATTERN_MS,
  NFC_MAX_NDEF_BYTES,
  SPEAKER_MAX_VOLUME,
  SPEAKER_PLAY_MAX_HZ,
  TORCH_MAX_DUTY_CYCLE,
  TORCH_MIN_STROBE_INTERVAL_MS,
  TTS_MAX_RATE,
  TTS_MAX_TEXT_LENGTH,
  TTS_MIN_RATE,
  validateActuatorCommand,
  type ActuatorCommandResult,
  type ActuatorSafetyCode,
  type DeviceCommand,
} from "../device-actuator-safety.js";
export {
  DEVICE_STREAM_KIND,
  MAX_DEVICE_STREAM_CHUNK_BYTES,
  MAX_DEVICE_STREAM_PAYLOAD_BYTES,
  DeviceStreamFrameError,
  decodeDeviceStreamFrame,
  encodeDeviceStreamFrame,
  frameDeviceStreamPayload,
  type DeviceStreamFrame,
  type DeviceStreamSampleKind,
} from "../device-stream-framing.js";
export {
  sanitizeCameraFrame,
  sanitizeMotionSamples,
  sanitizePcmSample,
  type RawCameraFrame,
  type RawCameraFrameInput,
  type RawMotionInput,
  type RawMotionSampleOut,
  type RawPcmInput,
  type RawPcmSample,
} from "../device-fingerprint.js";
export {
  adaptStreamAdmission,
  admittedWithinHeadroom,
  allDeviceClassIds,
  bandwidthProfileFor,
  decideStreamAdmission,
  degradationLadderFor,
  demandBps,
  selectPlane,
  supplyBps,
  type AdmissionDecision,
  type AdmissionDecisionKind,
  type AdaptationInput,
  type LinkSupply,
  type StreamDemand,
  type StreamPlane,
} from "../device-admission.js";
export {
  initialRemoteGrantStore,
  isRemoteGrantLive,
  remoteGrantKey,
  stepRemoteGrantStore,
  type RemoteDeviceGrant,
  type RemoteGrantEvent,
  type RemoteGrantPhase,
} from "../device-remote.js";
export {
  initialShareOfferStore,
  isShareOfferLive,
  shareOfferPermits,
  stepShareOfferStore,
  type ShareOffer,
  type ShareOfferEvent,
  type ShareOfferPhase,
  type ShareTargetKind,
} from "../device-share.js";
export {
  PAYMENT_AID_BLOCKLIST,
  NfcPaymentAidError,
  assertAidAllowed,
  isPaymentAidBlocked,
  normalizeAid,
  validateNfcApduCommand,
  type NfcApduCommand,
} from "../device-nfc-apdu.js";
