/* eslint-disable */
// Generated by scripts/generate-device-registry.mjs — do not edit.
// Source: specs/spec-device/registry/device-classes.json

export interface DeviceCapabilityDefinition {
  readonly id: "device:location" | "device:location:precise" | "device:ambient-light" | "device:camera" | "device:camera:frames" | "device:microphone" | "device:microphone:pcm" | "device:motion" | "device:motion:samples" | "device:torch" | "device:speaker" | "device:speaker:pcm" | "device:tts" | "device:stt" | "device:haptics" | "device:battery" | "device:screen-capture" | "device:screen-capture:frames" | "device:nfc" | "device:nfc:apdu" | "device:biometric" | "device:proximity" | "device:barometer" | "device:thermometer" | "device:hygrometer" | "device:thermal" | "device:stream" | "device:remote";
  readonly description: string;
  readonly classId: string | null;
  readonly tierId: string | null;
  readonly consentClass: "low" | "elevated" | "sensitive";
  readonly isDefaultTier: boolean;
}

export const DEVICE_CAPABILITY_DEFINITIONS = [
  {
    "id": "device:location",
    "description": "Host-mediated geolocation. Default tier is quantized coarse (~1 km); precise is a separate elevated grant. (default tier; consent: low).",
    "classId": "location",
    "tierId": "coarse",
    "consentClass": "low",
    "isDefaultTier": true
  },
  {
    "id": "device:location:precise",
    "description": "Host-mediated geolocation. Default tier is quantized coarse (~1 km); precise is a separate elevated grant. (precise tier; consent: elevated).",
    "classId": "location",
    "tierId": "precise",
    "consentClass": "elevated",
    "isDefaultTier": false
  },
  {
    "id": "device:ambient-light",
    "description": "Quantized ambient illuminance in lux, rate-capped at 1 Hz. (default tier; consent: low).",
    "classId": "ambient-light",
    "tierId": "quantized",
    "consentClass": "low",
    "isDefaultTier": true
  },
  {
    "id": "device:camera",
    "description": "Camera. Default derived tier yields barcodes, motion events, and counts — not full frames. (default tier; consent: elevated).",
    "classId": "camera",
    "tierId": "derived",
    "consentClass": "elevated",
    "isDefaultTier": true
  },
  {
    "id": "device:camera:frames",
    "description": "Camera. Default derived tier yields barcodes, motion events, and counts — not full frames. (frames tier; consent: sensitive).",
    "classId": "camera",
    "tierId": "frames",
    "consentClass": "sensitive",
    "isDefaultTier": false
  },
  {
    "id": "device:microphone",
    "description": "Microphone. Default derived tier yields level, VAD, tone/DTMF, and transcript — not raw PCM. (default tier; consent: elevated).",
    "classId": "microphone",
    "tierId": "derived",
    "consentClass": "elevated",
    "isDefaultTier": true
  },
  {
    "id": "device:microphone:pcm",
    "description": "Microphone. Default derived tier yields level, VAD, tone/DTMF, and transcript — not raw PCM. (pcm tier; consent: sensitive).",
    "classId": "microphone",
    "tierId": "pcm",
    "consentClass": "sensitive",
    "isDefaultTier": false
  },
  {
    "id": "device:motion",
    "description": "Fused motion (accel/gyro/magnetometer). Default derived tier is orientation and events at ≤ 10 Hz. (default tier; consent: elevated).",
    "classId": "motion",
    "tierId": "derived",
    "consentClass": "elevated",
    "isDefaultTier": true
  },
  {
    "id": "device:motion:samples",
    "description": "Fused motion (accel/gyro/magnetometer). Default derived tier is orientation and events at ≤ 10 Hz. (samples tier; consent: sensitive).",
    "classId": "motion",
    "tierId": "samples",
    "consentClass": "sensitive",
    "isDefaultTier": false
  },
  {
    "id": "device:torch",
    "description": "Camera torch / flashlight. Strobe rate hard-capped below photosensitive-epilepsy thresholds. (default tier; consent: elevated).",
    "classId": "torch",
    "tierId": "control",
    "consentClass": "elevated",
    "isDefaultTier": true
  },
  {
    "id": "device:speaker",
    "description": "Audio output. Default play tier accepts asset ids or TTS text — not arbitrary PCM carriers. (default tier; consent: elevated).",
    "classId": "speaker",
    "tierId": "play",
    "consentClass": "elevated",
    "isDefaultTier": true
  },
  {
    "id": "device:speaker:pcm",
    "description": "Audio output. Default play tier accepts asset ids or TTS text — not arbitrary PCM carriers. (pcm tier; consent: sensitive).",
    "classId": "speaker",
    "tierId": "pcm",
    "consentClass": "sensitive",
    "isDefaultTier": false
  },
  {
    "id": "device:tts",
    "description": "Text-to-speech service composing speaker. Text length and rate are bounded. (default tier; consent: elevated).",
    "classId": "tts",
    "tierId": "speak",
    "consentClass": "elevated",
    "isDefaultTier": true
  },
  {
    "id": "device:stt",
    "description": "Speech-to-text service composing microphone. Transcript is the derived microphone tier. (default tier; consent: elevated).",
    "classId": "stt",
    "tierId": "transcript",
    "consentClass": "elevated",
    "isDefaultTier": true
  },
  {
    "id": "device:haptics",
    "description": "Haptic feedback. Duty-cycle capped. (default tier; consent: low).",
    "classId": "haptics",
    "tierId": "pattern",
    "consentClass": "low",
    "isDefaultTier": true
  },
  {
    "id": "device:battery",
    "description": "Coarse battery buckets only — precise curves are a fingerprinting vector. (default tier; consent: low).",
    "classId": "battery",
    "tierId": "coarse",
    "consentClass": "low",
    "isDefaultTier": true
  },
  {
    "id": "device:screen-capture",
    "description": "Screen capture. Always requires an explicit per-session region picker in host chrome. (default tier; consent: sensitive).",
    "classId": "screen-capture",
    "tierId": "derived",
    "consentClass": "sensitive",
    "isDefaultTier": true
  },
  {
    "id": "device:screen-capture:frames",
    "description": "Screen capture. Always requires an explicit per-session region picker in host chrome. (frames tier; consent: sensitive).",
    "classId": "screen-capture",
    "tierId": "frames",
    "consentClass": "sensitive",
    "isDefaultTier": false
  },
  {
    "id": "device:nfc",
    "description": "NFC / card reader. APDU tier is sensitive and rejects payment AIDs at the driver. (default tier; consent: elevated).",
    "classId": "nfc",
    "tierId": "ndef",
    "consentClass": "elevated",
    "isDefaultTier": true
  },
  {
    "id": "device:nfc:apdu",
    "description": "NFC / card reader. APDU tier is sensitive and rejects payment AIDs at the driver. (apdu tier; consent: sensitive).",
    "classId": "nfc",
    "tierId": "apdu",
    "consentClass": "sensitive",
    "isDefaultTier": false
  },
  {
    "id": "device:biometric",
    "description": "Biometric assertion only. Templates never leave the OS enclave; there is no raw tier. (default tier; consent: elevated).",
    "classId": "biometric",
    "tierId": "assertion",
    "consentClass": "elevated",
    "isDefaultTier": true
  },
  {
    "id": "device:proximity",
    "description": "Near/far proximity scalar, rate-capped. (default tier; consent: low).",
    "classId": "proximity",
    "tierId": "near-far",
    "consentClass": "low",
    "isDefaultTier": true
  },
  {
    "id": "device:barometer",
    "description": "Atmospheric pressure scalar in hPa, rate-capped. (default tier; consent: low).",
    "classId": "barometer",
    "tierId": "pressure",
    "consentClass": "low",
    "isDefaultTier": true
  },
  {
    "id": "device:thermometer",
    "description": "Ambient temperature scalar in °C, rate-capped. (default tier; consent: low).",
    "classId": "thermometer",
    "tierId": "celsius",
    "consentClass": "low",
    "isDefaultTier": true
  },
  {
    "id": "device:hygrometer",
    "description": "Relative humidity percent scalar, rate-capped. (default tier; consent: low).",
    "classId": "hygrometer",
    "tierId": "humidity",
    "consentClass": "low",
    "isDefaultTier": true
  },
  {
    "id": "device:thermal",
    "description": "Coarse device thermal buckets only — precise curves are a fingerprinting vector. (default tier; consent: low).",
    "classId": "thermal",
    "tierId": "coarse",
    "consentClass": "low",
    "isDefaultTier": true
  },
  {
    "id": "device:stream",
    "description": "Stream any already-held device data to a peer. Never implied by a device grant alone.",
    "classId": null,
    "tierId": null,
    "consentClass": "sensitive",
    "isDefaultTier": false
  },
  {
    "id": "device:remote",
    "description": "Request a device on a peer's host. Confers nothing on the serving host.",
    "classId": null,
    "tierId": null,
    "consentClass": "sensitive",
    "isDefaultTier": false
  }
] as const satisfies ReadonlyArray<DeviceCapabilityDefinition>;

export type DeviceCapability = typeof DEVICE_CAPABILITY_DEFINITIONS[number]["id"];
